no-resolv
no-hosts
domain-needed
bogus-priv
local=/rac.test/
host-record=rac1,rac1.rac.test,10.203.0.11
host-record=rac2,rac2.rac.test,10.203.0.12
host-record=rac1-vip,rac1-vip.rac.test,10.203.0.21
host-record=rac2-vip,rac2-vip.rac.test,10.203.0.22
host-record=rac-scan,rac-scan.rac.test,10.203.0.31
host-record=rac-scan,rac-scan.rac.test,10.203.0.32
host-record=rac-scan,rac-scan.rac.test,10.203.0.33
host-record=rac1-priv1,10.203.1.11
host-record=rac2-priv1,10.203.1.12
host-record=rac1-priv2,10.203.2.11
host-record=rac2-priv2,10.203.2.12
